apiVersion: v1
kind: Pod
metadata:
  name: demo-pod
spec:
  containers:
    - name: web
      image: demo-web:latest
      ports:
        - containerPort: 8080
        - containerPort: 2222

    - name: db
      image: mysql:8.0
      env:
        - name: MYSQL_DATABASE
          value: "A-DOEUNG_Sreypy-db"
        - name: MYSQL_ROOT_PASSWORD
          value: "Hello@123"
      ports:
        - containerPort: 3306