- name: Deploy to Web Server
  hosts: web
  become: true

  tasks:
    - name: Pull latest code
      git:
        repo: https://github.com/Sreypy/Final_DevOps.git
        dest: /app
        force: yes

    - name: Restart application
      shell: |
        systemctl restart myapp